#ifndef CONFIG_H
#define CONFIG_H

//SensorCollection ParameterList
#define SENSORCOLLECTION_PARAMETER_TEMPLATE         "NAME;MEASURE;UNIT;MIN;MAX;OTHERS_PARAMS"
#define SENSORCOLLECTION_PARAMETER_COMMENT_LINE     "#"
#define SENSORCOLLECTION_PARAMETER_GROUP_DIVIDER    ";\\s{0,}"






#define MONITORING_DELAY            10000    //10sec

#define ARDUINO_UNO_VENDOR_ID       9025
#define ARDUINO_UNO_PRODUCT_ID      67
#define ARDUINO_UNO_BAUDRATE        115200





#define DATA_WAITING_DELAY          5000    //5sec
#define ERROR_COUNT_LIMIT           3

#endif // CONFIG_H
